# Modified from ComplexHeatmap::AnnotationFunction
# fun should be generated by a function factory
# In this way, all variables should imported in the function environment
chstat_anno_fn <- function(
    fun, fun_name = "", which = NULL, cell_fun = NULL,
    n = NA, data_scale = c(0, 1),
    subset_rule = NULL, subsettable = NULL,
    width = NULL, height = NULL, show_name = TRUE) {
    anno <- methods::new("AnnotationFunction")
    which <- match.arg(which, c("column", "row"))
    anno@which <- which
    anno@fun_name <- fun_name
    if (ComplexHeatmap::ht_opt$verbose) {
        cli::cli_inform("construct AnnotationFunction with {.fn {fun_name}}")
    }
    anno_size <- anno_width_and_height(which, width, height, unit(1, "cm"))
    anno@width <- anno_size$width
    anno@height <- anno_size$height
    anno@show_name <- show_name
    anno@n <- n
    anno@data_scale <- data_scale
    if (!is.null(cell_fun)) {
        fun <- function(index, k, n) {
            n <- length(index)
            for (i in seq_along(index)) {
                pushViewport(cheat_viewport(
                    x = i / n, width = 1 / n,
                    just = switch(which,
                        column = "right",
                        row = "bottom"
                    ),
                    default.units = "npc"
                ))
                cell_fun(index[i])
                popViewport()
            }
        }
        subsettable <- TRUE
    }
    anno@var_env <- environment(fun)
    if (length(as.list(formals(fun))) == 1) {
        formals(fun) <- alist(index = , k = 1, n = 1)
    }
    anno@fun <- fun
    if (is.null(subset_rule)) {
        for (nm in names(anno@var_env)) {
            if (is.matrix(anno@var_env[[nm]])) {
                anno@subset_rule[[nm]] <- ComplexHeatmap::subset_matrix_by_row
            } else if (inherits(anno@var_env[[nm]], "gpar")) {
                anno@subset_rule[[nm]] <- subset_gp
            } else if (is.vector(anno@var_env[[nm]])) {
                if (length(anno@var_env[[nm]]) > 1) {
                    anno@subset_rule[[nm]] <- ComplexHeatmap::subset_vector
                }
            }
        }
    } else {
        for (nm in names(subset_rule)) {
            anno@subset_rule[[nm]] <- subset_rule[[nm]]
        }
    }
    if (is.null(subsettable)) {
        if (length(anno@subset_rule)) {
            anno@subsettable <- TRUE
        }
    } else {
        anno@subsettable <- subsettable
    }
    return(anno)
}
